define({
	root: {
		inputvalidator_mandatory_input: "This field is required",
		inputvalidator_invalidip_poolname: "Can only contain letters, numbers, underscores or hyphens",
		inputvalidator_invalid_ip_address: "Invalid IP address",
		inputvalidator_invalid_ip_address_v6: "Invalid IPv6 address",
		inputvalidator_max_100_char: "Maximum 100 characters allowed",
		addippooldialog_cancel: "Cancel",
		addippooldialog_save: "Save",
		addippooldialog_pool_name: "IP Pool Name",
		addippooldialog_pool_type: "Type",
		addippooldialog_pool_generic: "Generic",
		addippooldialog_pool_tunnel: "Tunnel",
		addippooldialog_ip_subnet: "IP Subnet",
		addippooldialog_ipv6_subnet: "IPv6 Subnet",
		addippooldialog_ipv4_subnet: "IPv4 Subnet",
		addippooldialog_ipv4: "IPv4",
		addippooldialog_ipv6: "IPv6",
		addippooldialog_cidr_prefix: "CIDR Prefix",
		addippooldialog_gateway_ip: "Gateway IP Address",
		addippooldialog_ip_address_space: "IP Address Space",
		addippooldialog_v6_help_text: "Tunnel Type is supported for IPv4 pools only. If IPv6 is selected, all the below fields will have to be IPv6 format.",
		addippooldialog_dhcp_server: "DHCP Server(s)",
		addippooldialog_dns_server: "DNS Server(s)",
		addippooldialog_overlapping: "Overlapping",
		addippooldialog_edit_ip: "Edit IP Pool",
		addippooldialog_add_ip: "Add IP Pool",
		addippooldialog_add_ip_addr: "Add IP Address {labelVal}?",
		addippooldialog_add_ip_addr1: "Add IP Address {labelVal}?",
		addippooldialog_add_ip_address: "Add IP Address",
		addippooldialog_add_ip_address_v6: "Add IP Address",
		addippooldialog_detail_ips_available: "IPs Abailable",
		addippooldialog_detail_pool_cidr: "Pool CIDR",
		addippooldialog_detail_na: "NA",
		addippooldialog_detail_gateway: "Gateway",
		ippooltablecomponent_name: "Name",
		ippooltablecomponent_type: "Type",
		ippooltablecomponent_generic: "Generic",
		ippooltablecomponent_tunnel: "Tunnel",
		ippooltablecomponent_ip_subnet_mask: "IP Subnet Mask",
		ippooltablecomponent_ipv4: "IPv4",
		ippooltablecomponent_ipv6: "IPv6",
		ippooltablecomponent_ipv4_subnet: "IPv4 Subnet",
		ippooltablecomponent_ipv6_subnet: "IPv6 Subnet",
		ippooltablecomponent_subnet_filter: "IP Subnet (v4 or v6)",
		ippooltablecomponent_type_filter: "Subnet Type",
		ippooltablecomponent_gateway: "Gateway",
		ippooltablecomponent_dhcp_server: "DHCP Server",
		ippooltablecomponent_dns_server: "DNS Server",
		ippooltablecomponent_free_count: "Free Count",
		ippooltablecomponent_overlapping: "Overlapping",
		ippooltablecomponent_actions: "Actions",
		ippooltablecomponent_delete: "Delete",
		ippooltablecomponent_add: "Add",
		ippooltablecomponent_edit: "Edit",
		ippooltablecomponent_import: "Import from IPAM Server",
		ippooltablecomponent_export: "Export",
		ippooltablecomponent_import_csv: "Import from CSV file",
		ippooltablecomponent_yes: "Yes",
		ippooltablecomponent_no: "No",
		ippooltablecomponent_ip_addr: "IP Address Pools",
		ippooltablecomponent_ipam: "IPAM server is not configured. Do you want to proceed with the configuration?",
		ippooltablecomponent_delete_pool: "Are you sure you want to delete this pool?",
		importcsvdialog_title: "Import IP Address Pools",
		importcsvdialog_description: "Choose a CSV containing the list of IP Pools available",
		importcsvdialog_template: "Download Template",
		importcsvdialog_cancel: "Cancel",
		importcsvdialog_import: "Import",
		globalippoolreducer_updated_ip: "Updated IP Pool Successfully",
		globalippoolreducer_created_ip: "Created IP Pool Successfully",
		globalippoolreducer_updating: "updating",
		globalippoolreducer_creating: "creating",
		globalippoolreducer_deleted_succes_pool: "Deleted IP Pool Successfully",
		globalippoolreducer_imported: "Imported IP Pool(s) Successfully",
		globalippoolreducer_imported_error_msg: "`Error importing IP Pool(s): {nameCountData}",
		globalippoolreducer_imported_no: "No IP Pools selected for import.",
		globalpoolcomponent_add_ip: "Add IP Pool",
		globalpoolcomponent_ip_addr: "IP Address Pools",
		globalpoolcomponent_yes: "Yes",
		globalpoolcomponent_no: "No",
		globalpoolcomponent_ipam: "IPAM server is not configured. Do you want to proceed with the configuration?",
		reserveippooldialog_add_ip_address: "IP Address Pool Name",
		reserveippooldialog_ip_address_space: "IP Address Space",
		reserveippooldialog_ip_address_space_ipv4: "IPv4 (Default)",
		reserveippooldialog_ip_address_space_ipv6: "IPv6",
		reserveippooldialog_ipv6_subnet: "IPv6",
		reserveippooldialog_ipv4_subnet: "IPv4",
		reserveippooldialog_global_pool: "Global Pool",
		reserveippooldialog_cidr_noofip: "CIDR Prefix / Number of IP Addresses",
		reserveippooldialog_cidr_prefix: "CIDR Prefix",
		reserveippooldialog_noofip: "Number of IP Addresses",
		reserveippooldialog_not_number: "Not a number",
		reserveippooldialog_search_cidr: "Search CIDR",
		reserveippooldialog_detail_ips_available: "IPs available",
		reserveippooldialog_detail_pool_cidr: "Pool CIDR",
		reserveippooldialog_detail_global_pool: "Global Pool",
		reserveippooldialog_detail_dhcp_server: "DHCP Server(s)",
		reserveippooldialog_detail_dns_server: "DNS Server(s)",
		reserveippooldialog_detail_gateway: "Gateway",
		reserveippooldialog_detail_na: "NA",
		reserveippooldialog_ip_address_space_message:
			"Check both IPv4 and IPv6 to create a dual-stack pool. If the pool is used for infra VN, or if the fabric contains devices that don’t support IPv6, check only IPv4.",
		reserveippooldialog_slaacsupport: "SLAAC Support",
		reserveippooldialog_hint_subnet_v6: "For Example - 2001:db8::1234",
		reserveippooldialog_hint_subnet_v4: "For Example - 1.2.2.3",
		reserveippooldialog_release_pool: "Do you want to proceed with release of the IP Pool?",
		reserveippooldialog_remove_pool: "Do you want to proceed with removal of the IP Pool association?",
		reserveippooldialog_tunnel_reserve_help: "Tunnel pools are not available for reserving for Site(s).",
		reserveippooldialog_reserve_ip: "Reserve IP Pool",
		reserveippooldialog_cancel: "Cancel",
		reserveippooldialog_reserve: "Reserve",
		siteippoolcomponent_reserve_ip: "Reserve IP Pool",
		siteippoolcomponent_ip_addr: "IP Address Pools",
		subpooltablecomponent_ip_addr: "IP Address Pools",
		subpooltablecomponent_name: "Name",
		subpooltablecomponent_ip_subnet: "IP Subnet Mask",
		subpooltablecomponent_ipv4: "IPv4 only",
		subpooltablecomponent_ipv6: "IPv6",
		subpooltablecomponent_dual_stack: "Dual-Stack",
		subpooltablecomponent_ipv4_subnet: "IPv4 Subnet",
		subpooltablecomponent_ipv6_subnet: "IPv6 Subnet",
		subpooltablecomponent_subnet_filter: "IP Subnet (v4 or v6)",
		subpooltablecomponent_type_filter: "Subnet Type",
		subpooltablecomponent_ips_available: "IPs available",
		subpooltablecomponent_type: "Type",
		subpooltablecomponent_global_ip: "Global IP Pool",
		subpooltablecomponent_free_count: "Free Count",
		subpooltablecomponent_overlapping: "Overlapping",
		subpooltablecomponent_inherited: "Inherited from",
		subpooltablecomponent_reserve_ip: "Reserve IP Pool",
		subpooltablecomponent_actions: "Actions",
		subpooltablecomponent_remove: "Remove",
		subpooltablecomponent_pool_assoc: "Do you want to proceed with removal of the IP Pool association?",
		subpooltablecomponent_release: "Release",
		subpooltablecomponent_ip_pool_alert: "Do you want to proceed with release of the IP Pool?",
		subpooltablecomponent_remove_pool_assoc: "Remove IP pool association",
		subpooltablecomponent_release_ip_pool: "Release IP Pool",
		siteippoolreducer_common_setting: "Save to common settings failed!!",
		siteippoolreducer_reserved_ip: "Reserved IP pool succesfully",
		siteippoolreducer_updated_ip: "Updated IP pool successfully",
		siteippoolreducer_failed_ippool: "Failed to release IP pool: {nameCountData}",
		siteippoolreducer_removed_ip: "Removed IP Pool association succesfully",
		siteippoolreducer_released_ip: "Released IP Pool succesfully",
		siteippoolreducer_remove_ip_assoc: "Failed to remove IP Pool association}",
		ipAddresspoolutil_generic: "Generic",
		ipAddresspoolutil_lan: "LAN",
		ipAddresspoolutil_management: "Management",
		ipAddresspoolutil_service: "Service",
		ipAddresspoolutil_wan_internal: "WAN-Internal",
		timezonereducer_timezone_field: "Time Zone fields cant be empty",
		spprofilelist_unsaved_changes:
			"There are un-saved changes on this page and you will lose all these changes. Are you sure you want to leave this page?",
		spprofilelist_profile_name: "Profile Name",
		spprofilelist_wan_provider: "WAN Provider",
		spprofilelist_model: "Model",
		spprofilelist_reset: "Reset",
		spprofilelist_save: "Save",
		spprofilelist_add: "Add",
		spprofilereducer_require_error_msg: "Please fill in the required fields",
		spprofilereducer_require_field_msg: "This field is required",
		spprofilereducer_invalid_field: "Invalid Field",
		spprofilereducer_something_wrong: "Ooops!!! Something went wrong. Please try again.",
		spprofilereducer_field_require: "field is required",
		sppsettingscomponent_qos: "QoS",
		sppsettingsreducer_qos: "QoS",
		notificationsreducer_failed_notification: "Failed to load notifications",
		filterpopover_upcoming: "Upcoming",
		filterpopover_inprogress: "In Progress",
		filterpopover_success: "Success",
		filterpopover_failed: "Failed",
		filterpopover_all: "All",
		filterpopover_cancel: "Cancel",
		filterpopover_apply: "Apply",
		taskitem_upcoming: "Upcoming",
		taskitem_inprogress: "In Progress",
		taskitem_sucess: "Success",
		taskitem_failed: "Failed",
		taskitem_nodescription: "No description",
		taskitem_cancel: "Cancel",
		taskitem_scheduled: "Scheduled at {nameCountDynamicData}",
		taskitem_created: "Created On {0} by {1}",
		taskitem_no_details: "No details.",
		tasklist_yes: "Yes",
		tasklist_no: "No",
		tasklist_schedule_task: "Do you want to proceed with cancelling the scheduled task?",
		taskmanager_scheduled_tasks: "Scheduled Tasks",
		taskmanager_notification: "Notifications",
		taskreducer_status: "Status",
		taskreducer_type: "Type",
		taskreducer_task_name: "Task Name",
		clicred_add: "Add",
		clicred_title: "CLI Credentials",
		clicredtable_actions: "Actions",
		clicredtable_edit: "Edit",
		clicredtable_delete: "Delete",
		clicredtable_ok: "Ok",
		clicredtable_cancel: "Cancel",
		clicredtable_confirm_delete_alert: "Are you sure you want to delete?",
		httpcredtable_actions: "Actions",
		httpcredtable_edit: "Edit",
		httpcredtable_delete: "Delete",
		httpcredtable_ok: "Ok",
		httpcredtable_cancel: "Cancel",
		httpcredtable_confirm_delete_alert: "Are you sure you want to delete?",
		httpcredwritetable_actions: "Actions",
		httpcredwritetable_edit: "Edit",
		httpcredwritetable_delete: "Delete",
		httpcredwritetable_ok: "Ok",
		httpcredwritetable_cancel: "Cancel",
		httpcredwritetable_confirm_delete_alert: "Are you sure you want to delete?",
		snmpcredtable_actions: "Actions",
		snmpcredtable_edit: "Edit",
		snmpcredtable_delete: "Delete",
		snmpcredtable_ok: "Ok",
		snmpcredtable_cancel: "Cancel",
		snmpcredtable_confirm_delete_alert: "Are you sure you want to delete?",
		snmpreadtable_actions: "Actions",
		snmpreadtable_edit: "Edit",
		snmpreadtable_delete: "Delete",
		snmpreadtable_ok: "Ok",
		snmpreadtable_cancel: "Cancel",
		snmpreadtable_confirm_delete_alert: "Are you sure you want to delete?",
		snmpreadtable_read_community: "Read Community",
		snmpwritetable_actions: "Actions",
		snmpwritetable_edit: "Edit",
		snmpwritetable_delete: "Delete",
		snmpwritetable_ok: "Ok",
		snmpwritetable_cancel: "Cancel",
		snmpwritetable_confirm_delete_alert: "Are you sure you want to delete?",
		snmpwritetable_write_community: "Write Community",
		credentialreducer_name: "Name / Description",
		credentialreducer_username: "Username",
		credentialreducer_password: "Password",
		credentialreducer_enable_password: "Enable Password",
		credentialreducer_type: "Type",
		credentialreducer_snmp_v2c: "SNMP v2c",
		credentialreducer_snmp_v3: "SNMP v3",
		credentialreducer_community_type: "Community Type",
		credentialreducer_read: "Read",
		credentialreducer_write: "Write",
		credentialreducer_read_community: "Read Community",
		credentialreducer_use_number_format: "Only alphanumeric and - _ . @ characters allowed.",
		credentialreducer_mode: "Mode",
		credentialreducer_noauth: "Authentication and Privacy",
		credentialreducer_authnopriv: "Authentication, No Privacy",
		credentialreducer_authpriv: "No Authentication, No Privacy",
		credentialreducer_auth_type: "Auth Type",
		credentialreducer_sha: "SHA",
		credentialreducer_md5: "MD5",
		credentialreducer_privacy_type: "Privacy Type",
		credentialreducer_des: "DES (not recommended)",
		credentialreducer_aes: "AES128",
		credentialreducer_auth_password: "Auth Password",
		credentialreducer_privacy_password: "Privacy Password",
		credentialreducer_port: "Port",
		credentialreducer_cli_created: "CLI Credential Created Successfully",
		credentialreducer_cli_updated: "CLI Credential Updated Successfully",
		credentialreducer_snmp_read_created: "SNMP Read Credential Created Successfully",
		credentialreducer_snmp_read_updated: "SNMP Read Credential Updated Successfully",
		credentialreducer_snmp_write_created: "SNMP Write Credential Created Successfully",
		credentialreducer_snmp_write_updated: "SNMP Write Credential Updated Successfully",
		credentialreducer_snmpv3_created: "SNMPV3 Credential Created Successfully",
		credentialreducer_snmpv3_updated: "SNMPV3 Credential Updated Successfully",
		credentialreducer_http_read_created: "HTTP(S) Read Credential Created Successfully",
		credentialreducer_http_read_updated: "HTTP(S) Read Credential Updated Successfully",
		credentialreducer_http_write_created: "HTTP(S) Write Credential Created Successfully",
		credentialreducer_http_write_updated: "HTTP(S) Write Credential Updated Successfully",
		credentialreducer_profile: "Credential Profile Deleted Succesfully",
		credentialreducer_mandatory: "{nameCountDataObj} is Mandatory",
		credentialreducer_credential:
			"Credential changes for site(s) impacted are initiated succesfully, refer to device inventory for status update.",
		credentialreducer_only_alpha: "<> and spaces are not allowed.",
		credentialreducer_min_8_char: "Minimum 8 Charcters",
		credentialreducer_only_num: "Only Numeric",
		credentialreducer_zero: "Cannot be Zero",
		credentialreducer_max_1000: "Maximum value is 1000",
		credentialreducer_allowed: "<> are not Allowed",
		credentialreducer_Special_characters: "Only alphanumeric, spaces and - _ . characters allowed.",
		credentialreducer_mandatory_error_msg: "{nameCountData} is Mandatory",
		credentialreducer_mandatory_des: "{nameCountDynamicData} is Mandatory",
		dcpdialog_cli_credentials: "CLI Credentials",
		dcpdialog_cli_warning:
			'WARNING: Do not use "admin" as the username for your device CLI credentials, if you are using ISE as your AAA server. If you do, this can result in you not being able to login to your devices.',
		dcpdialog_snmp_credentials: "SNMP Credentials",
		dcpdialog_http_credentials: "HTTP(S) Credentials",
		dcpdialog_cancel: "Cancel",
		dcpdialog_save: "Save",
		dcpdialog_got_it: "Got it!",
		dcpdialog_password_update:
			"Password Update & Recovery are currently beta features. In this release, the following features are supported:",
		dcpdialog_cli_update: "CLI - Device supporting IOS/IOSXR, AireOS, ASAV and WAAS",
		dcpdialog_ios_iosxr_update: "SNMPV2Read – Device supporting IOS/IOSXR, AireOS, ASAV and WAAS",
		dcpdialog_wlc_snmp_update: "SNMPV2Write – Device supporting IOS/IOSXR, AireOS and WAAS",
		dcpdialog_nfvis_update: "SNMPV3 – Device supporting IOS/IOSXR, AireOS and WAAS",
		dcpdialog_http_update: "HTTP(S) – NFVIS",
		dcpdialog_beta_features: "Beta Features",
		dcpdialog_apply: "Apply {nameCountDataObj}",
		dcpdialog_edit: "Edit {nameCountData}",
		devicecredentialtab_ok: "Ok",
		devicecredentialtab_settings_saved: "Settings saved successfully!",
		devicecredentialtab_credential_saving: "Please select at least one credential before saving.",
		devicecredentialtab_reset: "Reset",
		devicecredentialtab_save: "Save",
		dialogcontent_update_task: "Credential Update Task",
		dialogcontent_caution: "Caution:Credentials will change on applicable devices as per the schedule selected below.",
		dialogcontent_apply_credential: "Applying Credentials?",
		httpcred_add: "Add",
		httpcred_write: "HTTP(S) Write",
		httpcred_http_read: "HTTP(S) Read",
		httpcred_http_credential: "HTTP(S) Credentials",
		snmpcred_read: "SNMPV2C Read",
		snmpcred_write: "SNMPV2C Write",
		snmpcred_snmpv3: "SNMPV3",
		snmpcred_add: "Add",
		snmpcred_snmp_credential: "SNMP Credentials",
		defaultdata_ipAddress: "IP Address",
		defaultdata_secondaryipaddress: "Secondary IP Address",
		defaultdata_sharedsecret: "Shared Secret",
		defaultdata_port: "Port",
		defaultdata_domainname: "Domain Name",
		defaultdata_primaryipaddress: "Primary IP Address",
		defaultdata_aaa: "AAA Server",
		defaultdata_dns: "DNS Server",
		defaultdata_dhcp: "DHCP Server",
		defaultdata_netflowcollector: "Netflow Collector",
		defaultdata_ntp: "NTP Server",
		defaultdata_snmpTrap: "SNMP Trap",
		defaultdata_syslog: "SYSLOG Server",
		aaaitem_domain: "Domain Name",
		aaaitem_ip_addr_additional: "IP Address (Additional)",
		aaaitem_add_ip: "Add IP Address {nameCountDataObj}",
		aaaitem_ip_addr_prim: "IP Address (Primary)",
		aaaitem_shared_secret: "Shared Secret",
		aaaitem_reset: "Reset to default",
		aaaitem_change_secret: "Change Shared Secret",
		aaaitem_network: "Network",
		aaaitem_client: "Client/Endpoint",
		aaaitem_servers: "Servers",
		aaaitem_protocal: "Protocol",
		aaaitem_ise: "ISE",
		aaaitem_radius: "RADIUS",
		aaaitem_tacacs: "TACACS",
		aaaitem_fetching_aaa_details: "Fetching AAA details. Please wait...",
		aaaitem_network_caps: "NETWORK",
		aaaitem_client_endpoint: "CLIENT/ENDPOINT",
		aaaitem_no_aaa:
			'No AAA Servers configured. Please configure them first under <a href="" onClick={() => window.history.pushState(null, null, `/dna/systemSettings?st-systemSettings=settings&settings-item=authenticationPolicyServers`)}>System Settings.</a>',
		aaaitem_saved:
			'The last saved value {0} is in {1} state . Please check <a href="" onClick={() => window.history.pushState(null, null, `/dna/systemSettings?st-systemSettings=settings&settings-item=authenticationPolicyServers`)}>System Settings.</a>',
		aaaitem_saved_not_found:
			'The last saved value {0} is not found. Please check <a href="" onClick={() => window.history.pushState(null, null, `/dna/systemSettings?st-systemSettings=settings&settings-item=authenticationPolicyServers`)}>System Settings.</a>',
		aaaitem_no_ise:
			'No ISE Servers configured. Please configure them first under <a href="" onClick={() => window.history.pushState(null, null, `/dna/systemSettings?st-systemSettings=settings&settings-item=authenticationPolicyServers`)}>System Settings.</a>',
		netflowcollector_ip_addr1: "IP Address",
		netflowcollector_port: "Port",
		netflowcollector_helptext:
			"The IP address set here is the destination server for netflow export from network devices",
		netflowcollector_title: "Netflow Collector Server",
		aaaserver_title: "AAA Server",
		aaaserver_network: "Network",
		aaaserver_client: "Client/Endpoint",
		dnsserver_title: "DNS Server",
		dnsserver_domain_name: "Domain Name",
		dnsserver_primary: "Primary",
		dnsserver_ip_addr: "IP Address",
		dnsserver_secondary: "Secondary",
		networkreducer_dns: "DNS",
		networkreducer_dhcp: "DHCP",
		networkreducer_snmp_trap: "SNMP Trap",
		networkreducer_syslog: "SYSLOG",
		networkreducer_netflow_collector: "Netflow Collector",
		networkreducer_ntp: "NTP",
		networkreducer_invalid_field: "Invalid field",
		networkreducer_unknown_error: "An unknown error has occurred. Please try again.",
		networktab_setting_saved: "Settings saved successfully!",
		networktab_saving_setting: "Saving settings... Please wait...",
		networktab_ok: "OK",
		networktab_app_not_avail: "Application Package Not Available",
		networktab_setup_network:
			'Setup network properties like AAA, NTP, Syslog, Trap and Netflow using the "Add Servers" link. Once devices are discovered, DNA Center will deploy using these settings.',
		networktab_use_netword:
			"Use Network telemetry Dashboard to create and configure profiles on network devices, which enables telemetry specifically for DNA Assurance.",
		networktab_network_tele: "Network Telemetry",
		networktab_add_server: "Add Servers",
		networktab_reset: "Reset",
		networktab_save: "Save",
		networktab_settings: "Save Settings",
		networktab_package_not_installed: "It may be because the package is not installed. If this is the case, go to the",
		networktab_app_manager_link:
			'It may be because the package is not installed. If this is the case, go to the /<a href="" onClick={() => window.history.pushState(null, null, "/dna/systemSettings?st-systemSettings=applicationManagement&st-appMgmtTabContainer=tab_system-packages-and-updates")}>App Manager/</a> to install the following application(s) /<strong>Network Data Platform</strong>.',
		networktab_duplicate_ip: "{nameCountDataObj} has duplicate IP Addresses.",
		networktab_invalid: "{nameCountDynamicData} in {nameCountData3} is invalid.",
		networktab_to_install: " to install the following application(s) ",
		networktab_cisco_support: "If you are still having trouble, contact Cisco Support.",
		networktab_network_data: "Network Data Platform",
		networktab_item_fix: "Please fix the following items.",
		networktab_please_wait: "Please wait...",
		serveritem_ip_addr1: "IP Address",
		serveritem_additional: "Additional {nameCountDataObj}",
		serverlistdialog_add_servers: "Add Servers",
		serverlistdialog_cancel: "Cancel",
		serverlistdialog_ok: "OK",
		validators_invalid: "Invalid field",
		validators_duplicate: "Duplicate value",
		labels_private: "Private",
		labels_public: "Public",
		labels_gold: "Gold",
		labels_silver: "Silver",
		labels_bronze: "Bronze",
		labels_class_4: "4 Class",
		labels_class_5: "5 Class",
		labels_class_6: "6 Class",
		labels_class_8: "8 Class",
		networksettingscomponent_network: "Network",
		networksettingscomponent_device: "Device Credentials",
		networksettingscomponent_ip_addr: "IP Address Pools",
		networksettingscomponent_sp_profile: "SP Profiles",
		networksettingscomponent_network_setting: "Network Settings",
		networksettingscomponent_find_hierarchy: "Find Hierarchy",
		networksettingscomponent_global: "Global",
		networksettingscomponent_no_children: "No Children Found.",
		networksettingscomponent_inherited_set: "Inherited Settings",
		networksettingscomponent_ok: "OK",
		networksettingscomponent_dont_show: "Don't show again",
		spprofilesave_save: "Save",
		spprofilereset_reset: "Reset",
		spprofilecomponent_saving_setting: "Saving settings... Please wait...",
		spprofilecomponent_setting_saved: "Settings saved successfully!",
		toggler_title: "Toggle left panel",
		others_message: "Message of the day",
		others_motd: "The MOTD banner displays when users log into a device. Custom MOTD messages can be up to 40 lines. Each line must 80 alphanumerical characters or less, upper or lower case, with any special characters other than # and <.",
		others_time_zone: "Time Zone",
		others_helptext:"User can set a time zone for the selected site based on geographical location of the site. By default, server time is used in the time zone settings. Select from the list below to set a different one. The time zone is used while scheduling provisioning and update of devices.",
		syslog_server: "SYSLOG Server",
		snmp_trap_server: "SNMP Server",
		snmp_trap_helptext:
			"The IP address set here is the destination server for SNMP traps and messages from network devices",
		snmp_trap_label: "SNMP",
		syslog_label: "SYSLOG",
		bannertextreducer_message: "Message of the day",
		bannertextreducer_helptext: "Banner text cannot exceed more than 80 characters in a single line",
		timezone_label: "Time Zone",
		timezone_helptext:"User can set a time zone for the selected site based on geographical location of the site. By default, server time is used in the time zone settings. Select from the list below to set a different one.",
		bannertextreducer_motd:
			"The message-of-the-day (MOTD) banner is displayed when the user logs in to a device. You can enter the message upto 40 lines with 80 or less characters per line. The message is alphanumeric, case sensitive, and can contain special characters, except #",
		importippooldialog_select: "Select All",
		importippooldialog_ip_pool_cidr: "CIDR",
		importippooldialog_pool_name:"Name",
		importippooldialog_dhcp_server:"DHCP Server",
		importippooldialog_dns_server:"DNS Server",
		importippooldialog_import_ip: "Import IP Pools",
		importippooldialog_cancel: "Cancel",
		importippooldialog_import: "Import",
		importippooldialog_cidr: "CIDR",
		importippooldialog_retrive: "Retrieve",
		importippooldialog_cidr_optional:
			'Note: Enter a CIDR (Optional) and click on "Retrieve" to get the list of IP Pools available to import from {nameCountDataObj}.',
		importippooldialog_cidr_name: "Note: DNAC will add a default name if not retrieved from external IPAM Server.",
		dcpserver_title: "DHCP Server",
		dcpserver_label: "DHCP",
		reducer_aaa: "AAA",
		scheduleitem_edit: "Edit",
		scheduleitem_updated: "Last Updated On {nameCountDataObj} by {nameCountDynamicData}",
		scheduleitem_cancel: "Cancel",
		scheduledtaskstab_cancelled: "Cancelled Scheduled Task Successfully",
		scheduledtaskstab_cancelling_error: "Error cancelling scheduled task",
		toolbar_refresh: "Refresh",
		toolbar_filter: "Filter",
		toolbar_lastupdated: "Last updated: {nameCountDataObj}",
		scheduleitem_desc: "No description",
		editschedulecomponent_cancel: "Cancel",
		editschedulecomponent_save: "Save",
		editschedulecomponent_edit_schedule_time: "Edit Schedule Time",
		serveritem_ip_addr: "IP Address / FQDN",
		// dnsserver_ip_addr: "IP Address / FQDN",
		netflowcollector_ip_addr: "IP Address / FQDN",
		credentialreducer_error_msg:
			"At least one lower case, one upper case, one digit and a special character and must not contain <>@',:; or spaces.",
		api_config_description_existing_cli: "To get existing CLI Credential",
		api_config_description_new_cli: "To create new CLI Credential",
		api_config_description_update_cli: "To update device CLI Credential",
		api_config_description_delete_cli: "To delete device CLI Credential",
		api_config_description_snmpv2_read: "To get existing SNMPV2Read Credential",
		api_config_description_snmpv2_new: "To create new SNMPV2Read Credential",
		api_config_description_snmpv2_update: "To update device SNMPV2Read Credential",
		api_config_description_snmpv2_delete: "To delete device SNMPV2Read Credential",
		api_config_desc_snmpv2_existing_write: "To get existing SNMPV2Write Credential",
		api_config_description_snmpv2_write_new: "To create new SNMPV2Write Credential",
		api_config_desc_snmpv2_write_update: "To update device SNMPV2Write Credential",
		api_config_desc_snmpv2_write_delete: "To delete device SNMPV2Write Credential",
		api_config_description_snmpv3_exist: "To get existing SNMPV3 Credential",
		api_config_description_snmpv3_new: "To create new SNMPV3 Credential",
		api_config_description_snmpv3_update: "To update device SNMPV3 Credential",
		api_config_description_snmpv3_delete: "To delete device SNMPV3 Credential",
		api_config_description_httpread_create: "To Create http-read Credential",
		api_config_description_httpread_exist: "To get existing http-read Credential",
		api_config_description_httpread_update: "To update device http-read Credential",
		api_config_description_httpread_delete: "To delete device http-read Credential",
		api_config_description_httpwrite_exist: "To get existing http-write Credential",
		api_config_description_httpwrite_create: "To create new http-write Credential",
		api_config_description_httpwrite_update: "To update device http-write Credential",
		api_config_description_httpwrite_delete: "To delete device http-write Credential",
		api_config_description_setting: "To get common settings for site = Global",
		api_config_description_global: "To Create common settings for site = Global",
		api_config_description_new_ippool: "To create new ippool",
		api_config_description_exist_ippool: "To get existing ippool",
		api_config_description_ip_update: "To update existing IP",
		api_config_description_ip_delete: "To delete existing IP's",
		api_config_description_ip_reserve: "To delete reserve IP's",
		api_config_description_ipam: "To be used while configuration of IPAM ",
		api_config_description_get_ipam: "To be used to get configuration of IPAM ",
		api_config_description_external_ip: "To be used to get external IP's from either INFOBLOX/BLUECAT",
		api_config_description_bulk_ip: "To be used to insert bulk IP's into table",
		api_config_description_aaa_settiing: "To get the AAA Settings",
		api_config_description_instance: "To get the AAA Settings for given Instance Uuid",
		api_config_description_create_aaa: "To create AAA Settings",
		api_config_description_get_aaa: "To get the AAA Settings for instance Uuid",
		api_config_description_delete_aaa: "To delete AAA Settings for instance Uuid",
		api_config_description_retrive_psn: "To Retrieve the IPs for all of the PSN nodes associated with the given PAN IP",
		template_mapper_component_device_type: "Device Type",
		template_mapper_componente_duplicate_row_error: "Duplicate Row",
		template_mapper_component_template: "Template",
		template_mapper_component_add: "Add",
		template_mapper_component_edit: "Edit",
		template_mapper_component_remove: "Remove",
		template_mapper_component_attach_temp: "Attach Template(s)",
		template_mapper_component_tag_name: "Tag Name",
		credentialreducer_usernameregex: "^[0-9A-Za-z_.-]+$",
		credentialreducer_extractalphanumchar: "^[a-zA-Z0-9\\-\\.\\_\\s]+$",
		credentialreducer_extractAlphanum: "[^a-zA-Z0-9]",
		inputvalidator_ippoolname: "^[0-9A-Za-z_-]+$",
		inputvalidator_domain: "^([a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$",
		credentialreducer_username_regex: "^[0-9A-Za-z@_.-]+$",
		credentialreducer_password_regex: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*(_|[^\\w])).+$",
		networksettingsreducer_global: "Global",
		credentialreducer_extractPassword: "[<>\\s]",
		credentialreducer_extractNumeric: "[^0-9]",
		task_reducer_success_msg_updated: "Updated Scheduled Task Successfully",
		network_tab_nothing_to_save: "Nothing to Save",
		banner_txt_invalid_error_txt_msg: "Message of the day is invalid",
		sub_tbl_componet_gateway: "Gateway",
		sub_tbl_componet_dhcp_server: "DHCP Server",
		sub_tbl_componet_dns_server: "DNS Server",
		sub_tbl_componet_overlapping: "Overlapping",
		sub_tbl_componet_actions: "Actions",
		sub_tbl_componet_rvs_ip_pool: "Reserve IP Pool",
		rvs_pool_dialog_gateway_ip_address: "Gateway IP Address",
		rvs_pool_dialog_dhcp_servers: "DHCP Server(s)",
		rvs_pool_dialog_dns_servers: "DNS Server(s)",
		rvs_pool_dialog_edit_ip_pool: "Edit IP Pool",
		rvs_pool_dialog_cancel: "Cancel",
		rvs_pool_dialog_save: "Save",
		reducer_errortext_server_type: "Please select a server type",
		reducer_errortext_pls_select: "Please select",
		reducer_errortext_pls_slt_another_value: "Please select another value",
		networksettingscomponent_parent_site:
			"Settings displayed with the above icon have been inherited from a parent site. To view the parent site information, click the inherited icon next to the setting.",
		networksettingscomponent_child_site:
			"Changing inherited settings will only affect this site and all its children, but not the parent settings. Once changed, the settings cannot be inherited back from its parent.",
		aaaitem_aaa: "AAA",
		ippooltablecomponent_ip_pool: "Add IP Pool",
		select_placeholder: "Select...",
		no_results_text: "No results found",
		aaa_select_placeholder: "Select...",
		aaa_no_results_text: "No results found",
		valid_cidr: "Enter valid CIDR. e.g. 99.99.0.0/16",
		domain_name: "{bOpenTag}Domain name{bCloseTag} can only contain alphanumeric characters or hyphen.",
		valid_range: "Valid range for {bOpenTag}Primary/Secondary IP address{bCloseTag} is 1.0.0.0 - 223.255.255.255",
		subpooltablecomponent_edit: "Edit",
		reservesubpooldialog_or: "OR",
		save: "Save",
		saving: "Saving...",
		no_match_ip_pools: "No matching IP Pools found. Enter another CIDR and retrieve again.",
		subnet_rqrs_dhcp: "This subpool requires at least one DHCP Server",
		port_usage: "Use port from 1 to 65535.",
		unknown_error: "An unknown error has occurred. Please try again.",
		select_each_row:
			"In order to apply the credentials to the selected site, please select one row from the list below for each type and press the Save button.",
		tckt_pend: "Ticket Pending",
		tckt_appvd: "Ticket Approved",
		tckt_reject: "Ticket Rejected",
		tckt_status_na: "Ticket Status N/A",
		status_na: "Status N/A",
		scheduled_run_aft_apprv: "Scheduled to run after approval",
		scheduleitem_start_at: "Started at {nameCountDynamicData}",
		helpText_IPV6: "Supports both IPv4 and IPv6",
		bannertextreducer_checkboxLabel: "Do not override the existing motd banner on the device",
		ipam360dashlet_title: "IP Address Manager (IPAM)",
		ipam360dashlet_label_server_name: "Server Name",
		ipam360dashlet_label_server_url: "Server URL",
		ipam360dashlet_label_username: "Username",
		ipam360dashlet_label_provider: "Provider",
		ipam360dashlet_label_configure: "Configure",
		ipam360dashlet_label_manage: "Update",
		ipam360dashlet_label_as_of: "As of",
		ipam360dashlet_label_no_ipam: "No IPAM server configured.",
		ipam360dashlet_label_fetching_configuration: "Fetching configuration",
		api_config_description_get_ipam_config: "To get saved IPAM configuration",
		defaultdata_stealthwatchcollector: "Stealthwatch Collector",
		label_syslog_checkbox: "Cisco DNA Center as syslog server",
		label_snmp_checkbox: "Cisco DNA Center as snmp server"
	},
	ja: true,
	zh: true,
	ko: true
});
